INSERT INTO TEAM(TEAM_ID, TEAM_NAME) VALUES (1, 'DD unicorns');
INSERT INTO TEAM(TEAM_ID, TEAM_NAME) VALUES (2, 'Ray reopard');
INSERT INTO TEAM(TEAM_ID, TEAM_NAME) VALUES (3, 'V tigers');
INSERT INTO TEAM(TEAM_ID, TEAM_NAME) VALUES (4, 'Gold dragons');
INSERT INTO TEAM(TEAM_ID, TEAM_NAME) VALUES (5, 'Isaac phinix');
INSERT INTO TEAM(TEAM_ID, TEAM_NAME) VALUES (6, 'Woody dinos');
INSERT INTO TEAM(TEAM_ID, TEAM_NAME) VALUES (7, 'Cooper rions');
INSERT INTO TEAM(TEAM_ID, TEAM_NAME) VALUES (8, 'Penguins Dumbbells');

INSERT INTO GAME(HOME_TEAM_ID, HOME_TEAM_SCORE, AWAY_TEAM_ID, AWAY_TEAM_SCORE) VALUES (1, 0, 2, 0);
INSERT INTO GAME(HOME_TEAM_ID, HOME_TEAM_SCORE, AWAY_TEAM_ID, AWAY_TEAM_SCORE) VALUES (3, 0, 4, 0);
INSERT INTO GAME(HOME_TEAM_ID, HOME_TEAM_SCORE, AWAY_TEAM_ID, AWAY_TEAM_SCORE) VALUES (5, 0, 6, 0);
INSERT INTO GAME(HOME_TEAM_ID, HOME_TEAM_SCORE, AWAY_TEAM_ID, AWAY_TEAM_SCORE) VALUES (7, 0, 8, 0);
